{
    "name": "Brand Kit Manager",
    "summary": "Manage company brand kits from a dedicated module",
    "version": "19.0.1.0.0",
    "category": "Tools",
    "author": "Your Company",
    "license": "LGPL-3",
    "depends": ["base", "mail", "base_setup"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/brand_kit_sequence.xml",
        "data/default_brand_kit.xml",
        "views/brand_kit_views.xml",
        "views/brand_kit_preview_wizard_views.xml",
        "views/res_config_settings_views.xml",
    ],
    "installable": True,
    "application": True,
}
