{
    "name": "Brand Kit Manager",
    "summary": "Unified email branding with logo, colors, footer, and legal text",
    "version": "19.0.1.1.0",
    "category": "Tools",
    "author": "Mr.Abhi",
    "maintainer": "Mr.Abhi",
    "website": "https://github.com/Abhishekbandaranayaka/odoo-brand-kit-manager",
    "support": "info.ajconsulting.zynolo@gmail.com",
    "license": "LGPL-3",
    "price": 35.0,
    "currency": "USD",
    "images": [
        "static/description/banner.png",
        "static/description/thumbnail.png",
        "static/description/screenshots/brand_kit_manager_cover.png",
    ],
    "depends": ["base", "mail", "base_setup"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/brand_kit_sequence.xml",
        "data/default_brand_kit.xml",
        "data/mail_notification_layout_brand_kit.xml",
        "views/brand_kit_views.xml",
        "views/brand_kit_preview_wizard_views.xml",
        "views/res_config_settings_views.xml",
    ],
    "installable": True,
    "application": True,
}
